steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME', '-f', './Dockerfile', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args:
      - run
      - deploy
      - $_SERVICE_NAME
      - '--image=gcr.io/$PROJECT_ID/$_SERVICE_NAME'
      - '--platform=gke'
      - '--cluster=cluster-be'
      - '--cluster-location=asia-northeast1'
      - '--namespace=default'
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'

logsBucket: "gs://dev-building-logs"
