steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$SERVICE_NAME', '-f', '.docker/Dockerfile', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$SERVICE_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'api-searching', '--image', 'gcr.io/$PROJECT_ID/$SERVICE_NAME', '--platform', 'managed', '--region', '$_REGION', '--quiet']

images:
  - 'gcr.io/$PROJECT_ID/$SERVICE_NAME'
