version: "2"
services:
  app:
    container_name: api-searching
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/go/src/github.com/coding-challenge/api-searching
    ports:
      - 8080:8011
