FROM golang:1.20-alpine

ENV GO111MODULE on
ENV APP_ENV development
RUN apk add bash ca-certificates curl  g++ libc-dev autoconf automake libtool make
RUN mkdir -p /go/src/github.com/coding-challenge/api-searching

WORKDIR /go/src/github.com/coding-challenge/api-searching

ADD . .

RUN go mod init
RUN go mod tidy
RUN go mod vendor

RUN go install github.com/githubnemo/CompileDaemon@latest


ENTRYPOINT CompileDaemon -build="go build -o build/api ./main.go" -command="./build/api"
